// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKvA2Fn-8g2Quw7ue5A7eRYvmP8wv9CBk',
    appId: '1:336092925108:web:4431d0fa25bf1cdbff1be1',
    messagingSenderId: '336092925108',
    projectId: 'domo-8b336',
    authDomain: 'domo-8b336.firebaseapp.com',
    storageBucket: 'domo-8b336.firebasestorage.app',
    measurementId: 'G-2YJJMJVDNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8OOeDb6stRi6ne5tOCqTgUjn_YIK_0g',
    appId: '1:336092925108:android:88865192830e1329ff1be1',
    messagingSenderId: '336092925108',
    projectId: 'domo-8b336',
    storageBucket: 'domo-8b336.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKvA2Fn-8g2Quw7ue5A7eRYvmP8wv9CBk',
    appId: '1:336092925108:web:36a106187291f7c5ff1be1',
    messagingSenderId: '336092925108',
    projectId: 'domo-8b336',
    authDomain: 'domo-8b336.firebaseapp.com',
    storageBucket: 'domo-8b336.firebasestorage.app',
    measurementId: 'G-RCYE3BRCX1',
  );
}
